apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment
  namespace: k8s-lab
  labels:
    app: web
  annotations:
    descriptions: "Nginx deployment used for Kubernetes learning"

spec:
  replicas: 3

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web
        tier: frontend
        environment: learning
      annotations:
        purpose: "Demonstrate Pod metadata"

    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
